# action.yml
name: 'Get Branch Name and Check if is release branch'
description: 'Get current branch name and corresponding branch tag if needed.'
branding:
    icon: 'activity'  
    color: 'white'
outputs:
  branch:
    description: 'Current branch name'
  is_release_branch:
    description: 'The indicator whenever the branch is release branch'
runs:
  using: 'docker'
  image: 'Dockerfile'
