# action.yml
name: 'Get Branch Name and Check if is release branch'
description: 'Get current branch name and check if it is release branch.'
branding:
    icon: 'activity'  
    color: 'white'
inputs:
  branch:
    description: 'Branch to check. Default or empty value represents current github ref (${GITHUB_REF})'
    required: false
    default: 'master'
outputs:
  branch:
    description: 'Current branch name'
  is_release_branch:
    description: 'The indicator whenever the branch is release branch'
runs:
  using: 'docker'
  image: 'Dockerfile'
